### ISSUE TITLE
请问theta是怎么定义的？

### ISSUE THREAD

**Issue by chenwenhao99** [yingkunwu/R-YOLOv4#1]

**Comment by yingkunwu** [comment]
我定義在這裡哦 
https://github.com/kkkunnnnethan/R-YOLOv4/blob/4043582227f4f60eaec39cbb228b6dcbb30d7b64/tools/load.py#L129

x1 為物體正向左上角的座標 照著順時針旋轉依序為x2, x3, x4
算出弧度之後用arctan公式轉換成角度[-180, 180]，之後為了不讓-180跟180重複，我將角度範圍設定為(-180, 180]

**Comment by chenwenhao99** [comment]
感谢回答！ 这个项目对我帮助很大。

**Comment by chl916185** [comment]
代码是在-90到90度之间的，您解释的是-180～180啊

**Comment by yingkunwu** [comment]
> 代码是在-90到90度之间的，您解释的是-180～180啊

啊是的，對不起我講錯了。我將角度範圍設定在(-pi/2, pi/2] 。因為Bounding Box的形狀是對稱的，導致-pi/2 跟 pi/2會是一樣的狀況，所以我是用(-pi/2, pi/2]，而不是[-pi/2, pi/2]。
