### ISSUE TITLE
vertical_flip实现是不是不太对？

### ISSUE THREAD

**Issue by UnlightedOtaku** [yingkunwu/R-YOLOv4#10]
您好，最近我在可视化预处理过后的图片。但是发现vertical_flip之后的图片颜色不对。
以下三张分别是原图，您的vertical_flip实现，PIL实现。
![ori](https://user-images.githubusercontent.com/45728883/140026107-3d09917e-dbad-4b79-a4e1-42b826e290f0.png)
![v](https://user-images.githubusercontent.com/45728883/140027182-95200e2b-8dcb-4734-ad56-11f1e4b1dceb.png)
![v_PIL](https://user-images.githubusercontent.com/45728883/140027202-ad69df84-b892-42ea-9755-0c72ab440fda.png)

**Comment by UnlightedOtaku** [comment]
我打印了一下像素矩阵，发现您的vertical_flip可能把r通道和b通道弄反了
我想原本的
`images = torch.flip(images, [0, 1])`
应该改为
`images = torch.flip(images, [1])`

**Comment by yingkunwu** [comment]
你好，我剛剛也發現了！非常感謝你。
