### ISSUE TITLE
权重可以共享到百度云嘛

### ISSUE THREAD

**Issue by chl916185** [yingkunwu/R-YOLOv4#14]

**Comment by yingkunwu** [comment]
抱歉，我沒有百度云的帳號。你沒辦法用google雲端下載嗎？

**Comment by yuxin7** [comment]
您好，您下载到权重了吗？

**Comment by yuxin7** [comment]
> _No description provided._



> _未提供说明。_

您下载到权重了吗？

**Comment by yuxin7** [comment]
> 抱歉，我沒有百度云的帳號。你沒辦法用google雲端下載嗎？

国内现在好像没法从google上下载文件了
