### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by PJPomPom** [yingkunwu/R-YOLOv4#16]
![Snipaste_2021-11-25_15-17-15](https://user-images.githubusercontent.com/77728649/143396711-7c37b453-ab8d-4988-b1e9-dca767ac068e.png
![Snipaste_2021-11-25_15-17-01](https://user-images.githubusercontent.com/77728649/143396837-5fdf3f01-d766-46cd-87ed-d6b7029075c5.png)
![Snipaste_2021-11-25_15-00-46](https://user-images.githubusercontent.com/77728649/143396869-5e6aeb0d-bac9-47db-94b0-84c5a2d60897.png)
)
![image](https://user-images.githubusercontent.com/77728649/143397161-709ebb5a-9c18-4297-8a55-0dcb2ade8b57.png)

大佬，我将我找的数据集的xml转化为txt格式如下，然后train.py出现了问题：文件为空，请您帮我解答一下，谢谢

**Comment by yingkunwu** [comment]
你的資料夾裡面有yolov4.pth這個檔案嗎

**Comment by PJPomPom** [comment]
![image](https://user-images.githubusercontent.com/77728649/143398053-5f253783-023b-4b81-96b7-d5758755682f.png)
有喔

**Comment by yingkunwu** [comment]
我可以看一下yolov4.pth的檔案大小嗎

**Comment by PJPomPom** [comment]
0字节哦，大概是没下载好，我再试试

**Comment by PJPomPom** [comment]
![Snipaste_2021-11-25_15-42-53](https://user-images.githubusercontent.com/77728649/143400536-4fdd06ce-9871-42ef-91cf-687d55c6c488.png)
![Snipaste_2021-11-25_15-47-05](https://user-images.githubusercontent.com/77728649/143400544-34839dc6-eedd-4250-a7c5-13bf645d2952.png)

write函数只能写str格式嘛，报错说我格式错误，唉

**Comment by yingkunwu** [comment]
Have you solved your problems?

**Comment by PJPomPom** [comment]
没呀，我不知道这个load.py如何使用，他的作用是利用xml产生的txt，然后转化为ryolov4训练需要的txt嘛？

**Comment by PJPomPom** [comment]
没呀，我不知道这个load.py如何使用，他的作用是利用我自己xml产生的txt，然后将其转化为ryolov4训练需要的txt嘛？

**Comment by yingkunwu** [comment]
不是，它的作用是讀取已經從xml中轉化成txt的檔案，把txt中的資訊獨進dataloader裏面。關於如何把xml轉化成txt可以參考我的[程式碼](https://github.com/kunnnnethan/R-YOLOv4/issues/18#issuecomment-988433580)

**Comment by PJPomPom** [comment]
好的，谢谢大佬

**Comment by PJPomPom** [comment]
![image](https://user-images.githubusercontent.com/77728649/146120780-610a543c-ec4c-44e1-ba25-94d43d6d1eef.png)
大佬，这是我生成的txt，然后train报错了，是哪里的问题呢

**Comment by yingkunwu** [comment]
模型在訓練時只能將數字納入運算，請將Label的類別以Integer代替，替換後應該就能運算了。

**Comment by PJPomPom** [comment]
大佬，我改了标签，出现了如下错误
![image](https://user-images.githubusercontent.com/77728649/146126424-0580449d-8064-422e-9a74-23123cc38f80.png)
其次，使用detect.py后outputs文件夹无输出
![image](https://user-images.githubusercontent.com/77728649/146126966-faaf6e71-cb60-422c-8bcb-771626711ba4.png)

**Comment by yingkunwu** [comment]
第一個狀況我沒有遇過，有可能是python和opencv版本不一樣的關係。可以問一下你的python和opencv版本嗎？
另外你嘗試把augments.py裡面的第44, 45, 46行都改成像這種寫法-> hsv[1] = hsv[1] * sat 試試看

關於第二個狀況，可不可以幫我把[這行](https://github.com/kunnnnethan/R-YOLOv4/blob/62a8b7690b1c4684c217ccd564d66717174c6614/tools/plot.py#L75)的output_path變數print出來給我看，感謝。

**Comment by PJPomPom** [comment]
大佬你好，augments.py已修改，仍报错
![Snipaste_2021-12-17_11-26-05](https://user-images.githubusercontent.com/77728649/146489924-62345d72-47ae-48fd-bd24-148584b94555.png)

> 其次，我调试output_path变量输出无结果，不知道我做的对吗，恳请指正
![Snipaste_2021-12-17_12-35-58](https://user-images.githubusercontent.com/77728649/146490121-53a17d4a-c4f6-43f1-8576-41b7a69cea4d.png)

**Comment by yingkunwu** [comment]
I am sorry that you couldn't run my code properly. I need some time to fix your errors. In the meantime, could you try to solve it yourself? You are still welcome to report your questions anytime.

**Comment by yingkunwu** [comment]
I think I have solved your problems. Please pull the latest version code and run it again. Thanks!

**Comment by PJPomPom** [comment]
感謝大佬的回復，這將給我提供很大的幫助！
👍👍👍

**Comment by yuxin7** [comment]
> 感謝大佬的回復，這將給我提供很大的幫助！ 👍👍👍

大佬可以把你下载的权重给我发一份吗？

**Comment by PJPomPom** [comment]
大佬您好，我关闭了数据增强，和马赛克等操作，为什么训练到40轮以后出现这样的问题呢，损失直接没了，期待您的回复，谢谢！
recent:///abe870a697d17340193ce0db63367287
recent:///ea4d478fb304dd333376929f63367287
