### ISSUE TITLE
缺失标注数据集

### ISSUE THREAD

**Issue by Iipython** [yingkunwu/R-YOLOv4#17]
在/data/train中的示例数据集中，标注的每一行中只有位置信息而没有类别信息，请问程序是如何获得类别信息的

**Comment by yingkunwu** [comment]
我把不同的類別放在不同的資料夾裡，所以當我在取出image時我可以根據這點來幫他們做類別標注。在tools/load.py的程式碼中，我是在split_data()這個函式中將從不同資料夾取出的照片做label的。
