### ISSUE TITLE
数据格式转化问题

### ISSUE THREAD

**Issue by zjs210** [yingkunwu/R-YOLOv4#18]
您好，我想问一下使用labimg2标注图片得到的xml文件怎么转化为程序中使用的txt文件，能发一下代码嘛？

**Comment by yingkunwu** [comment]
你好，下列代碼供你參考哦

```python
import xml.etree.ElementTree as ET
import glob
import numpy as np
import os

if __name__ == "__main__":
    data_dir = "data/add/"
    files = sorted(glob.glob(data_dir + "*.xml"))
    #for file in files:
    #    os.remove(file)
    #exit(1)
    for file in files:
        tree = ET.parse(file)
        root = tree.getroot()

        with open(data_dir + file.split("/")[-1].split(".")[0] + ".txt", 'w') as f:
            for object in root.findall('object'):
                label = object.find('name').text
                x = object.find('robndbox').find('cx').text
                y = object.find('robndbox').find('cy').text
                w = object.find('robndbox').find('w').text
                h = object.find('robndbox').find('h').text
                a = float(object.find('robndbox').find('angle').text)
                while a > np.pi:
                    a = a - np.pi
                while a <= -np.pi:
                    a = a + np.pi
                line_to_write = x + " " + y + " " + w + " " + h + " " + str(a) + " " + label + '\n'
                f.write(line_to_write)
```

**Comment by zjs210** [comment]
> 你好，下列代碼供你參考哦
> 
> ```python
> import xml.etree.ElementTree as ET
> import glob
> import numpy as np
> import os
> 
> if __name__ == "__main__":
>     data_dir = "data/add/"
>     files = sorted(glob.glob(data_dir + "*.xml"))
>     #for file in files:
>     #    os.remove(file)
>     #exit(1)
>     for file in files:
>         tree = ET.parse(file)
>         root = tree.getroot()
> 
>         with open(data_dir + file.split("/")[-1].split(".")[0] + ".txt", 'w') as f:
>             for object in root.findall('object'):
>                 label = object.find('name').text
>                 x = object.find('robndbox').find('cx').text
>                 y = object.find('robndbox').find('cy').text
>                 w = object.find('robndbox').find('w').text
>                 h = object.find('robndbox').find('h').text
>                 a = float(object.find('robndbox').find('angle').text)
>                 while a > np.pi:
>                     a = a - np.pi
>                 while a <= -np.pi:
>                     a = a + np.pi
>                 line_to_write = x + " " + y + " " + w + " " + h + " " + str(a) + " " + label + '\n'
>                 f.write(line_to_write)
> ```

谢谢，您好，我想问一下单目标检测的话，需要修改程序的哪些地方

**Comment by zjs210** [comment]
> 你好，下列代碼供你參考哦
> 
> ```python
> import xml.etree.ElementTree as ET
> import glob
> import numpy as np
> import os
> 
> if __name__ == "__main__":
>     data_dir = "data/add/"
>     files = sorted(glob.glob(data_dir + "*.xml"))
>     #for file in files:
>     #    os.remove(file)
>     #exit(1)
>     for file in files:
>         tree = ET.parse(file)
>         root = tree.getroot()
> 
>         with open(data_dir + file.split("/")[-1].split(".")[0] + ".txt", 'w') as f:
>             for object in root.findall('object'):
>                 label = object.find('name').text
>                 x = object.find('robndbox').find('cx').text
>                 y = object.find('robndbox').find('cy').text
>                 w = object.find('robndbox').find('w').text
>                 h = object.find('robndbox').find('h').text
>                 a = float(object.find('robndbox').find('angle').text)
>                 while a > np.pi:
>                     a = a - np.pi
>                 while a <= -np.pi:
>                     a = a + np.pi
>                 line_to_write = x + " " + y + " " + w + " " + h + " " + str(a) + " " + label + '\n'
>                 f.write(line_to_write)
> ```

谢谢，您好，我想问一下单目标检测的话，需要修改程序的哪些地方

**Comment by zjs210** [comment]
> 你好，下列代碼供你參考哦
> 
> ```python
> import xml.etree.ElementTree as ET
> import glob
> import numpy as np
> import os
> 
> if __name__ == "__main__":
>     data_dir = "data/add/"
>     files = sorted(glob.glob(data_dir + "*.xml"))
>     #for file in files:
>     #    os.remove(file)
>     #exit(1)
>     for file in files:
>         tree = ET.parse(file)
>         root = tree.getroot()
> 
>         with open(data_dir + file.split("/")[-1].split(".")[0] + ".txt", 'w') as f:
>             for object in root.findall('object'):
>                 label = object.find('name').text
>                 x = object.find('robndbox').find('cx').text
>                 y = object.find('robndbox').find('cy').text
>                 w = object.find('robndbox').find('w').text
>                 h = object.find('robndbox').find('h').text
>                 a = float(object.find('robndbox').find('angle').text)
>                 while a > np.pi:
>                     a = a - np.pi
>                 while a <= -np.pi:
>                     a = a + np.pi
>                 line_to_write = x + " " + y + " " + w + " " + h + " " + str(a) + " " + label + '\n'
>                 f.write(line_to_write)
> ```

你好，这种格式对吗？
0.0 0.4385334375 0.5997470833333334 0.0465478125 0.7692329166666667 17

**Comment by zjs210** [comment]
> 你好，下列代碼供你參考哦
> 
> ```python
> import xml.etree.ElementTree as ET
> import glob
> import numpy as np
> import os
> 
> if __name__ == "__main__":
>     data_dir = "data/add/"
>     files = sorted(glob.glob(data_dir + "*.xml"))
>     #for file in files:
>     #    os.remove(file)
>     #exit(1)
>     for file in files:
>         tree = ET.parse(file)
>         root = tree.getroot()
> 
>         with open(data_dir + file.split("/")[-1].split(".")[0] + ".txt", 'w') as f:
>             for object in root.findall('object'):
>                 label = object.find('name').text
>                 x = object.find('robndbox').find('cx').text
>                 y = object.find('robndbox').find('cy').text
>                 w = object.find('robndbox').find('w').text
>                 h = object.find('robndbox').find('h').text
>                 a = float(object.find('robndbox').find('angle').text)
>                 while a > np.pi:
>                     a = a - np.pi
>                 while a <= -np.pi:
>                     a = a + np.pi
>                 line_to_write = x + " " + y + " " + w + " " + h + " " + str(a) + " " + label + '\n'
>                 f.write(line_to_write)
> ``

**Comment by zjs210** [comment]
你好，xml转化成这种格式对吗？
0.0 0.4385334375 0.5997470833333334 0.0465478125 0.7692329166666667 17

**Comment by yingkunwu** [comment]
> 你好，xml转化成这种格式对吗？
> 0.0 0.4385334375 0.5997470833333334 0.0465478125 0.7692329166666667 17

沒有錯哦 依序是 [x, y, w, h, angle, label]

**Comment by zjs210** [comment]
> > 你好，xml转化成这种格式对吗？
> > 0.0 0.4385334375 0.5997470833333334 0.0465478125 0.7692329166666667 17
> 
> 沒有錯哦 依序是 [x, y, w, h, angle, label]

你好，那个xml转txt的程序有问题，运行不了

**Comment by yingkunwu** [comment]
Please attach the error messages to your comment so that I can help you. Thanks!

**Comment by zjs210** [comment]
> Please attach the error messages to your comment so that I can help you. Thanks!

Traceback (most recent call last):
  File "G:/classification/R-YOLOv4/data/xml2txt.py", line 16, in <module>
    with open(data_dir + file.split("/")[-1].split(".")[0] + ".txt", 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'G:/classification/R-YOLOv4/data/xml-img2/xml-img2\\0001.txt'

**Comment by zjs210** [comment]
![image](https://user-images.githubusercontent.com/77560911/145925049-a6197efb-c239-4c2b-8bc1-01cde6d749f3.png)

**Comment by yingkunwu** [comment]
FileNotFoundError: [Errno 2] No such file or directory

這個錯誤是指xml的檔案不在你指定的檔案路徑內，你可以看一下你的xml檔案是不是有在你程式中指定的路徑：'G:/classification/R-YOLOv4/data/xml-img2/xml-img2\0001.txt。

**Comment by zjs210** [comment]
在的，

**Comment by zjs210** [comment]
> FileNotFoundError: [Errno 2] No such file or directory
> 
> 這個錯誤是指xml的檔案不在你指定的檔案路徑內，你可以看一下你的xml檔案是不是有在你程式中指定的路徑：'G:/classification/R-YOLOv4/data/xml-img2/xml-img2\0001.txt。

![image](https://user-images.githubusercontent.com/77560911/145926089-c5184ac7-deda-4d0a-a58a-75c1a18c1d69.png)

**Comment by zjs210** [comment]
> FileNotFoundError: [Errno 2] No such file or directory
> 
> 這個錯誤是指xml的檔案不在你指定的檔案路徑內，你可以看一下你的xml檔案是不是有在你程式中指定的路徑：'G:/classification/R-YOLOv4/data/xml-img2/xml-img2\0001.txt。

去掉xml-img2后面的/，就变成这样了，也没有txt数据生成
![image](https://user-images.githubusercontent.com/77560911/145926282-4c74151a-059a-42b4-a917-6fbcc922829f.png)

**Comment by yingkunwu** [comment]
xml-img2資料夾中沒有嗎？

**Comment by zjs210** [comment]
> xml-img2資料夾中沒有嗎？

没有，没有生成txt

**Comment by yingkunwu** [comment]
抱歉，這邊我就真的不知道了，再麻煩您自行debug一下
