### ISSUE TITLE
检测数据保存问题

### ISSUE THREAD

**Issue by jiayaohua** [yingkunwu/R-YOLOv4#19]
![QQ截图20211222160550](https://user-images.githubusercontent.com/96518960/147057936-eebe7bc0-da8b-41bc-a3b5-bc220b5f8785.png)检测过的图片并没有保存
![P0489](https://user-images.githubusercontent.com/96518960/147058199-6a572b46-f2e4-4d38-b9c7-d38e1263cf22.png)
怎样会出现这种检测后的图片，谢谢

**Comment by yingkunwu** [comment]
已針對此問題做了修改[這](https://github.com/kunnnnethan/R-YOLOv4/commit/04bf236ce476f4c6c19d0d753cf8e049fc63a22a)，幫我pull下來再跑一次看看，感謝！

**Comment by jiayaohua** [comment]
想问下刚才是修改了那一块，我没找到您修改的点

**Comment by jiayaohua** [comment]
感谢大佬

**Comment by jiayaohua** [comment]
你使用的环境是tensorflow？

**Comment by jiayaohua** [comment]
![HF](https://user-images.githubusercontent.com/96518960/147186518-efd563e5-f935-48c4-84c1-aa4bf1dab9f2.png)
![DFNGN](https://user-images.githubusercontent.com/96518960/147186522-06c31fbb-c5cc-4a1e-958c-5df02dce94ef.png)
这是我训练自己数据集，出现的问题，麻烦再看下我第二张图片中的标签格式正确吗？感谢！

**Comment by jiayaohua** [comment]
![ffb](https://user-images.githubusercontent.com/96518960/147186898-33b86466-0f69-4c32-808f-36c74ade20f8.png)
这里的[-1,13]貌似是把txt中的坐标和角度，reshape成13位的，就是这里出现错误

**Comment by yingkunwu** [comment]
> 你使用的环境是tensorflow？

我的是pytorch哦
