### ISSUE TITLE
Visualize boxes 

### ISSUE THREAD

**Issue by candyotter** [yingkunwu/R-YOLOv4#2]
This is great!

How did you visualize the bounding boxes on the images at the end of detect.py ?
Should I be getting a txt file out with the labels?

Thank you!

**Comment by yingkunwu** [comment]
Hi, thank you for liking my project. It's the OpenCV cv.drawContours function that allows me to plot it. I have implemented it here https://github.com/kkkunnnnethan/R-YOLOv4/blob/4043582227f4f60eaec39cbb228b6dcbb30d7b64/tools/plot.py#L43.
After the detection, I saved the coordinates of those bounding boxes in a list and input it into cv.drawContours for plotting contours. Feel free to ask more if it wasn't helpful to you.
