### ISSUE TITLE
数据集txt标签问题

### ISSUE THREAD

**Issue by jiayaohua** [yingkunwu/R-YOLOv4#20]
![iii](https://user-images.githubusercontent.com/96518960/147209805-fc28ec98-ae65-41c9-be1b-82f9110fb2e6.png)
这个模型好像必须使用这种13列的标签，我试了用rolabelimg2制作的5列标签，他就会报错，错误如下：
![ppp](https://user-images.githubusercontent.com/96518960/147209844-ed72e32d-52b8-4106-85c7-cd38ec6f7cce.png)

**Comment by jiayaohua** [comment]
这个13列的标签，各列都代表啥呀。实在弄不明白，只能再次麻烦您了

**Comment by kunnnnethan** [comment]
你必須修改部分程式碼才可以跑客製化的label格式。我創了一個新的branch叫做custom_dataset，在這個branch中我修改了load.py，應該可以達到你的需求。你可以把在custom_dataset branch版本的code pull下來跑跑看，希望有幫助到你。

**Comment by yingkunwu** [comment]
你必須要更改load.py內的程式碼才能夠讀取客製化的資料集。根據這個問題我已經做了update，現在只需要在train.py後面多加上一個--custom_dataset的flag，應該就可以成功的執行你客製化的程式碼。希望有幫助到你。

**Comment by jiayaohua** [comment]
![1](https://user-images.githubusercontent.com/96518960/147349310-6ce6dd9c-66ed-44b4-ba05-7eb5bbd03bf1.png)
这种数据集标签格式，大佬你知道是如何制作的吗？

**Comment by yingkunwu** [comment]
我不知道欸，這是官方製作的數據集。 如果你需要用自己客製化的資料集做訓練的話，你可以去我寫的Readme.md中看要如何訓練。
