### ISSUE TITLE
训练结果问题

### ISSUE THREAD

**Issue by Aphelios-Larouen** [yingkunwu/R-YOLOv4#21]

**Comment by yingkunwu** [comment]
可能是你訓練時跟檢測時使用的照片大小不太一樣，你可以檢查一下模型在訓練時跟檢測時看到的物件大小是否不會相差太多。

**Comment by Aphelios-Larouen** [comment]
分辨率是一样的，都是600×600

**Comment by yingkunwu** [comment]
你在訓練的時候有用mosaic嗎？

**Comment by Aphelios-Larouen** [comment]
我是直接运行的您的train.py

**Comment by Aphelios-Larouen** [comment]
我看您自定义的trash数据集的检测效果很好，想在我的数据集上测试下，没有进行更改。

**Comment by yingkunwu** [comment]
那我可以問您您的照片原始的resolution嗎，因為如果有使用mosaic augmentation的話，決定圖片的尺寸會是sample size。如果您的原始圖片的尺寸很大的話，每個crop出來的物件就會被放到很大。你可以用這個[function](https://github.com/kunnnnethan/R-YOLOv4/blob/main/experiments/display_inputs.py)來確認一下你的圖片被讀取之後的樣子嗎？

**Comment by Aphelios-Larouen** [comment]
我试试看

**Comment by Aphelios-Larouen** [comment]
![image](https://user-images.githubusercontent.com/82483548/154199294-177f2359-dc91-4855-86b1-f0d4f082c427.png)
文件里有class.names为什么报错

**Comment by yingkunwu** [comment]
檔名要改成你自己的。要把 '/' 改成 '\' 。你有重新訓練過模型嗎？

**Comment by Aphelios-Larouen** [comment]
我训练来着

**Comment by Aphelios-Larouen** [comment]
![image](https://user-images.githubusercontent.com/82483548/154201093-c26af603-1286-482e-9beb-1073a31d3831.png)
请问这样修改对吗？运行还是报错。我之前学的是机械，不太会计算机编程。

**Comment by Aphelios-Larouen** [comment]
请问您有其他联系方式吗？比如QQ或微信，方便向您请教。

**Comment by yingkunwu** [comment]
> 请问您有其他联系方式吗？比如QQ或微信，方便向您请教。

沒問題的，我有微信。給我條碼我掃你嗎？

**Comment by Aphelios-Larouen** [comment]
13930372923我的微信

**Comment by Aphelios-Larouen** [comment]
![cc6bd713508654fe5801b4dcb14327a](https://user-images.githubusercontent.com/82483548/154204517-9a312af9-1e96-4e5c-be2a-8270ab0954cf.jpg)
