### ISSUE TITLE
DOTA1.0train，test下来ap不是很高

### ISSUE THREAD

**Issue by wangjiawen-123** [yingkunwu/R-YOLOv4#25]
楼主好，我用的这个代码+DOTA1.0，裁剪成1024尺寸，epochs=50，AP最后的结果很低，并与您的outputs对比十分不理想，nms=0.2，最后杂框很多，我不知道是哪里出问题了
![mAP](https://user-images.githubusercontent.com/73467053/163771427-5502e67f-a036-4b0a-bde6-00f61dc62f78.png)
![image](https://user-images.githubusercontent.com/73467053/163771694-8607648e-0f53-4ea8-bcfa-a7078991f63d.png)

**Comment by yingkunwu** [comment]
可以看一下你的train.py 的 argument怎麼設的嗎

**Comment by wangjiawen-123** [comment]
> 
整体您的代码我没有怎么改动，train里面augmentation就是lib里的没动，mosaic也是，不知道什么原因，我用的这个代码大概是1月份您的版本，不知道后期有没有改进
![image](https://user-images.githubusercontent.com/73467053/164018658-2aa500f4-4cf3-4324-b4d1-8429c40e440b.png)
![image](https://user-images.githubusercontent.com/73467053/164018846-653ab6b1-d353-436d-830f-99f2f521ab7f.png)

**Comment by yingkunwu** [comment]
我主要是想看sample_size的部分
