### ISSUE TITLE
How to call the local camera to realize real-time detection？

### ISSUE THREAD

**Issue by Aphelios-Larouen** [yingkunwu/R-YOLOv4#27]

**Comment by yingkunwu** [comment]
The method to call the local camera varies with the type of the camera you are using. Therefore it is hard for me to answer your question without knowing which camera you were using for detection. Also, this kind of code is not relative to the model and should totally be written by yourself as the function of your code should be specific to your needs.

**Comment by Aphelios-Larouen** [comment]
I sent a message to your wechat. Please check it when you are free.
