### ISSUE TITLE
大佬 请问你可以教我如何写一个test.py吗？

### ISSUE THREAD

**Issue by MheadHero** [yingkunwu/R-YOLOv4#28]
你好，我是来自马来西亚的学生。你是我少数看到现在还活跃的yolov4大佬，我想跟你请教如何写一个test.py。因为我在跟着一个tianxiaomo的yolov4但是他没有做test.py。所以我的教授要求我去写一个，但是我看来看去（比如说看他的train.py，比如说看你的train.py和test.py，和别人的），我真的不懂我在看什么。（哭）

**Comment by yingkunwu** [comment]
我這參考這個的 [code](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/detect.py)
其實大致上的code我也都沒有改過，你可以去看看他寫的。不過基本上就是按照著計算mAP的方式去做implement而已～

**Comment by MheadHero** [comment]
哇 没想到你回复了 不过那个link坏了勒 xd 谢谢你先！

**Comment by yingkunwu** [comment]
似乎有換了一個作者維護，新的地址在這https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/test.py！
