### ISSUE TITLE
训练custom数据集的问题

### ISSUE THREAD

**Issue by ciomphzx** [yingkunwu/R-YOLOv4#30]
大佬你好，我训练自己的数据集运行train.py文件时出现以下报错：
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
pytorch的版本是1.7.0，请问是版本的原因吗

**Comment by yingkunwu** [comment]
應該不是版本問題，你確定你的路徑是正確的嗎？

**Comment by ciomphzx** [comment]
> 

我把权重文件换成ryolo.pth可以正常训练了，请问代码从零训练应该从哪里进行修改

**Comment by yingkunwu** [comment]
你真要全部從頭開始訓練的話 你就在這個function中[連結](https://github.com/kunnnnethan/R-YOLOv4/blob/ab85440b135cd029c8151d6a0d120632db0b35bc/train.py#L52)，把54 55行留著其他全部刪掉就可以了。
不過就我的經驗來說，重零開始訓練效果會差非常的多，而且不易收斂。

**Comment by ciomphzx** [comment]
好的，非常感谢

**Comment by ciomphzx** [comment]
HRSC2016数据集训练了100epoch，检测时出现了一个目标有重复的框的情况，将检测时的nms_thres设置为0也出现重复框，请问这是什么原因 训练集图片626张 测试集444张

**Comment by yingkunwu** [comment]
應該是那個目標同時被認為是多重類別？ 例如車子被模型判斷成車子跟卡車

**Comment by ciomphzx** [comment]
把类别设置为了4种 同一个目标被识别成两种类型

**Comment by yingkunwu** [comment]
> 把类别设置为了4种 同一个目标被识别成两种类型

那就沒辦法了。這個模型的在accuracy方面還需要加強，尤其是對比較小的物品。

**Comment by ciomphzx** [comment]
小目标没有出现这种情况 图像中的小目标被识别出来了 大的目标出现了这种情况
