### ISSUE TITLE
Reg loss calculation

### ISSUE THREAD

**Issue by sonalrpatel** [yingkunwu/R-YOLOv4#32]
The regression loss considered is `smooth_l1_loss (for angle) - ciou (for xywh)`.

Considering that, should not the **ciou loss** calculation be `ciou = bbox_loss_scale * (0.0 - ciou)` 
instead of `ciou = bbox_loss_scale * (1.0 - ciou)` in below line?
https://github.com/kunnnnethan/R-YOLOv4/blob/ab85440b135cd029c8151d6a0d120632db0b35bc/model/yololayer.py#L113

https://github.com/kunnnnethan/R-YOLOv4/blob/ab85440b135cd029c8151d6a0d120632db0b35bc/model/yololayer.py#L119

https://github.com/kunnnnethan/R-YOLOv4/blob/ab85440b135cd029c8151d6a0d120632db0b35bc/model/yololayer.py#L197

With the current implementation, the effective regression loss calculation is `smooth_l1_loss (for angle) + 1 - ciou (for xywh)`.

**Comment by yingkunwu** [comment]
Sorry if the notation confused you. The algorithm of CIoU loss is shown as follow. Hence the negative sign.
<img width="287" alt="Screenshot 2022-12-03 at 2 15 34 PM" src="https://user-images.githubusercontent.com/61398396/205460172-defc5c80-809a-4e6f-a541-5a094485eedf.png">
