### ISSUE TITLE
训练到40轮损失nan

### ISSUE THREAD

**Issue by PJPomPom** [yingkunwu/R-YOLOv4#33]
![2022-09-30 12-34-16屏幕截图](https://user-images.githubusercontent.com/77728649/193191571-6d27685b-b1a3-4d54-a426-f9f57f469b88.png)
![2022-09-30 12-30-29屏幕截图](https://user-images.githubusercontent.com/77728649/193191588-1087b846-257b-42f7-9123-63a3ea188581.png)
大佬您好！为什么训练到40轮出现这样的问题呢？我关闭了马塞克增强等方法，期待您的回复，谢谢！

**Comment by yingkunwu** [comment]
你是用哪個資料集呢？

**Comment by PJPomPom** [comment]
> 你是用哪個資料集呢？

您好，我用的是dota，然后筛选出了5类目标用于训练，但是我减小学习率后没有这种情况呢，请问是为何呢？

**Comment by yingkunwu** [comment]
DOTA的資料分佈比較複雜，所以在更高維的空間中會比較難收斂。我也不知道為何減小學習率可以避免這種情況，但是減小學習率後會造成模型的精確度降低，所以如何讓模型避免在學習時發生這種情況可能是需要研究一下。

**Comment by PJPomPom** [comment]
> DOTA的資料分佈比較複雜，所以在更高維的空間中會比較難收斂。我也不知道為何減小學習率可以避免這種情況，但是減小學習率後會造成模型的精確度降低，所以如何讓模型避免在學習時發生這種情況可能是需要研究一下。

感谢您的回复，您能分享一下您的dota训练权重嘛，我想测试一下您的权重的检测效果，方便的话我给您我的邮箱1041479372@qq.com

**Comment by yingkunwu** [comment]
我使用的權重都在這了 [link](https://github.com/kunnnnethan/R-YOLOv4/blob/0640745f318b89a3b0041e893f35246604d499d8/experiments/DOTA.sh)

**Comment by PJPomPom** [comment]
> 我使用的權重都在這了 [link](https://github.com/kunnnnethan/R-YOLOv4/blob/0640745f318b89a3b0041e893f35246604d499d8/experiments/DOTA.sh)

您好，我想您方便提供一下你训练dota数据集训练好的权重文件吗，就那个ryolov4.pth，你可以给我谷歌网盘链接，看您怎么方便，谢谢
![bb45d0f218f5a4e461572ab7ec0007e](https://user-images.githubusercontent.com/77728649/196664005-3d3007a5-e54b-4fee-b85e-df003b2e6c1b.jpg)

**Comment by PJPomPom** [comment]
> 我使用的權重都在這了 [link](https://github.com/kunnnnethan/R-YOLOv4/blob/0640745f318b89a3b0041e893f35246604d499d8/experiments/DOTA.sh)

您好，我想您方便提供一下你训练dota数据集训练好的权重文件吗，就那个ryolov4.pth，你可以给我谷歌网盘链接，看您怎么方便，谢谢

还想问您一下，你训练DOTA数据集使用的是原图吗，还是裁剪过后进行训练的？
![bb45d0f218f5a4e461572ab7ec0007e](https://user-images.githubusercontent.com/77728649/196666001-e282ca41-d0f3-4a64-b713-6a00aede12d7.jpg)

**Comment by pjpshizhu** [comment]
您好，我还想问您一下，使用display_inputs.py对输入的图像可视化，显示输入的图像目标的原始标注框出现错位了，请问是什么问题呢？
![image](https://user-images.githubusercontent.com/96984448/197239854-691cdd05-db4d-4e24-97a1-b78e93d5ece5.png)

**Comment by yingkunwu** [comment]
> 您好，我还想问您一下，使用display_inputs.py对输入的图像可视化，显示输入的图像目标的原始标注框出现错位了，请问是什么问题呢？
> ![image](https://user-images.githubusercontent.com/96984448/197239854-691cdd05-db4d-4e24-97a1-b78e93d5ece5.png)

我認為可能只是ground truth本身的問題，可能準備資料集的人本來就沒標好，不然不會有大部分都匡對只有少部分匡錯的情況

**Comment by yingkunwu** [comment]
> > 我使用的權重都在這了 [link](https://github.com/kunnnnethan/R-YOLOv4/blob/0640745f318b89a3b0041e893f35246604d499d8/experiments/DOTA.sh)
> 
> 您好，我想您方便提供一下你训练dota数据集训练好的权重文件吗，就那个ryolov4.pth，你可以给我谷歌网盘链接，看您怎么方便，谢谢
> 
> 还想问您一下，你训练DOTA数据集使用的是原图吗，还是裁剪过后进行训练的？ ![bb45d0f218f5a4e461572ab7ec0007e](https://user-images.githubusercontent.com/77728649/196666001-e282ca41-d0f3-4a64-b713-6a00aede12d7.jpg)

請從[這裡](https://drive.google.com/file/d/1bVsDltjCJR9gcUjr33UIob10dKaK_c3V/view?usp=sharing)下載。我是使用mosaic augmentation做訓練的，所以訓練時使用的是剪裁的圖片。因此，預測時也是要用剪裁後的圖片。

**Comment by PJPomPom** [comment]
> 我使用的權重都在這了 [link](https://github.com/kunnnnethan/R-YOLOv4/blob/0640745f318b89a3b0041e893f35246604d499d8/experiments/DOTA.sh)

您好，我想您提供一下你训练dota数据集训练好的权重文件，就那个ryolov4.pth，你可以给我谷歌网盘链接，看您怎么方便，谢谢

感谢您的回复
