### ISSUE TITLE
box2 is sometimes empty causing assertions

### ISSUE THREAD

**Issue by diamantisk** [yingkunwu/R-YOLOv4#43]
I'm not sure if this is an issue or not. 
Using the full code from this project, I have tried to train the model to predict rotated bounding boxes on a custom dataset with only 2 classes.
After the first epoch and while the first training cycle completes, in the test cycle, I always get the following error:

     44 def skewiou(box1, box2):
     45 
---> 46     assert len(box1) == 5 and len(box2[0]) == 5
     47     # End of diamantis additions. if you remove that, please re enable assert.
     48 

IndexError: index 0 is out of bounds for dimension 0 with size 0

According to excessive debugging in order to see what is going wrong, I noticed that box2 is indeed empty causing the training process to crash. 
Model is always generates predictions for box2 too, I verified that in the step below using these 2 prints:
#print("box1:", detect[0, :5])
#print("box2:", detect[:, :5])
large_overlap = iou(detect[0, :5], detect[:, :5], nms_thres)

The issue happens when matrixes are passed to iou. It's not the happening from the start in the epoch, it successfully processes multiple times the data (meaning that it is not crashing at the first iteration inside post_process).

Any idea of what is going wrong or what I'm doing wrong would be indeed very helpful.

**Comment by yingkunwu** [comment]
Thank you for raising this issue. Yes, we are aware of this problem and are trying to fix it recently. Also, as we are working on improving the repository lately, many parts of the code will be changed. The latest version will be released in 1~2 days in the branch named "base". Please check it out then. Thanks!

**Comment by yingkunwu** [comment]
Hi @diamantisk , the bug has been fixed. Feel free to report other potential problems in the future.
