### ISSUE TITLE
请问您的yolov4的预训练权重是在什么数据集上训练的?

### ISSUE THREAD

**Issue by UnlightedOtaku** [yingkunwu/R-YOLOv4#5]
顺便给个小建议，tools/logger.py 中用的是tensorflow
不过我个人不太想再去装tensorflow
您可以了解一下torch.utils.tensorboard
```
# 官方示例代码
from torch.utils.tensorboard import SummaryWriter
import numpy as np

writer = SummaryWriter()

for n_iter in range(100):
    writer.add_scalar('Loss/train', np.random.random(), n_iter)
```

**Comment by yingkunwu** [comment]
是使用原YOLOv4作者預訓練的權重。網路上可以找到很多相關資訊說明要怎麼將原作者的權重轉換成PyTorch的.pth檔。因為我的模型架構有些名稱不太一樣，所以有經過另外的處理，不過權重的大小層數都是一樣的。

感謝你的建議！ 我會去了解一下
