### ISSUE TITLE
How does it work with m x n input image size ? 

### ISSUE THREAD

**Issue by naga24** [yingkunwu/R-YOLOv4#61]
I have 8k images, what should i pass in the img_size param of train.py ?

**Comment by yingkunwu** [comment]
The img_size parameter determines the size to which images will be resized. You have flexibility in specifying the size, as long as it's divisible by 32. However, given the large size of your images, it would be better to split your images into several images with smaller size to achieve better results from the model.

**Comment by naga24** [comment]
Yes, but how can i split the boxes corresponding the splitted images preserving the angle ?

**Comment by yingkunwu** [comment]
Sorry for the late reply. You can check out https://github.com/open-mmlab/mmrotate/blob/main/tools/data/dota/README.md to see how does that work. I used their code to generate split images for training as well. Hope this helps!

**Comment by naga24** [comment]
Yes thanks for that I did the same from Dota dev kit

**Comment by yingkunwu** [comment]
I have noticed that there are some bugs in the DOTA dev kit. I could not split ground truths according to images properly using DOTA dev kit. I would recommend you to validate it. If it works for you then never mind.
