### ISSUE TITLE
Values normalization

### ISSUE THREAD

**Issue by PrefectSol** [yingkunwu/R-YOLOv4#63]
It is not very clear what the input of the model is. I understand that in labels.txt The following is expected:
```
<class_id> <centerX/imgsz> <centerY/imgsz> <w/imgsz> <h/imgsz> <theta/360 or 2P?>
```
What is expected on theta?
Or maybe the values don't have to be normalized at all

**Comment by yingkunwu** [comment]
Hi, which labels.txt are you referring to? The expected data format is depending on different dataset. May I ask which dataset is the one you mentioned?

**Comment by PrefectSol** [comment]
> Hi, which labels.txt are you referring to? The expected data format is depending on different dataset. May I ask which dataset is the one you mentioned?

I don't use ready-made data sets, I'm trying to create my own

**Comment by PrefectSol** [comment]
> > Hi, which labels.txt are you referring to? The expected data format is depending on different dataset. May I ask which dataset is the one you mentioned?
> 
> I don't use ready-made data sets, I'm trying to create my own

That is, I am trying to create my own dataset, but I do not understand in what format the model is expected to be input

**Comment by yingkunwu** [comment]
For that you can look into this [line](https://github.com/kunnnnethan/R-YOLOv4/blob/c63523178ece4812b21385d456a79e5338ec3522/datasets/base_dataset.py#L159). This is what I passed to the model from PyTorch Dataset loader. If you want to create your own dataset, you can follow the workflow of the [custom dataset](https://github.com/kunnnnethan/R-YOLOv4/blob/c63523178ece4812b21385d456a79e5338ec3522/datasets/custom_dataset.py) that I created.

**Comment by PrefectSol** [comment]
thx
