### ISSUE TITLE
Train with single GPU

### ISSUE THREAD

**Issue by xiaofeng-c** [yingkunwu/R-YOLOv4#7]
Whether it can be trained in 1 GPU?

**Comment by yingkunwu** [comment]
I don't really understand your question but I guess yes it can; since I did not design the code for the purpose of multiprocessing.

**Comment by xiaofeng-c** [comment]
**Sorry,when i use the train.py,a error occur as follow:**
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

---- [Epoch 1/10] ----

Traceback (most recent call last):
  File "train.py", line 90, in <module>
    outputs, loss = model(imgs, targets)
  File "/home/dio/VSST/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/model.py", line 37, in forward
    x2, x10, x18 = self.head(x20, x13, x6)
  File "/home/dio/VSST/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/head.py", line 39, in forward
    x3 = torch.cat([x3, input2], dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 10.76 GiB total capacity; 9.49 GiB already allocated; 5.00 MiB free; 9.75 GiB reserved in total by PyTorch)
**and i try to modify the batch_size to 2 and use 2GPU,the error is:**
Traceback (most recent call last):
  File "train.py", line 90, in <module>
    outputs, loss = model(imgs, targets)
  File "/home/dio/VSST/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/model.py", line 38, in forward
    y1, loss1 = self.yolo1(x2, target)
  File "/home/dio/VSST/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/yololayer.py", line 194, in forward
    pred_boxes=pred_boxes, pred_cls=pred_cls, target=target
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/yololayer.py", line 111, in build_targets
    tconf = obj_mask.float()
RuntimeError: CUDA error: device-side assert triggered
do you know what wrong wiith it?

**Comment by yingkunwu** [comment]
Sorry, in the case of 2 GPU, I can't really be helpful to you because I have not tried to train a model with 2 GPU yet.

However in the first error, it means that you are using too much memory. Please try to reduce your batch size or image size. I am able to train the model with 7GB cuda memory under the following parameters setting: batch_size=4, subdivisions=4, image_size=416. 

If it still can't work, make sure to specify the --no_multiscale flag so that it [(here)](https://github.com/kunnnnethan/R-YOLOv4/blob/123c68a09ea09721750e31a2a8b0049c4836a20a/train.py#L122) would not allocate more memory while training. Hope this helps.

**Comment by xiaofeng-c** [comment]
Ok,thank you,i will try it.

**Comment by xiaofeng-c** [comment]
**I use the new version codes,and the question is:**
(pytorch1.7) dio@dio:~/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main$ python train.py
Namespace(batch_size=4, data_folder='data/train', epochs=50, img_size=416, lr=0.001, model_name='UCAS_AOD', subdivisions=4, weights_path='weights/pretrained/yolov4.pth')
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [34,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [36,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cuTraceback (most recent call last):
  File "train.py", line 169, in <module>
:84: operator(): block: [0,0,0], thread: [37,0    t.train()
  File "train.py", line 146, in train
,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu    outputs, loss = self.model(imgs, targets)
  File "/home/dio/VSST/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
:84: operator(): block: [0,0,0], thread: [38,0,0    result = self.forward(*input, **kwargs)
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/model.py", line 35, in forward
] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
    y1, loss1 = self.yolo1(x2, target)
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu  File "/home/dio/VSST/anaconda3/envs/pytorch1.7/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
:84: operator(): block: [0,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [40    result = self.forward(*input, **kwargs)
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/yololayer.py", line 181, in forward
,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [41,0    pred_boxes=pred_boxes, pred_cls=pred_cls, target=target, masked_anchors=masked_anchors
  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/yololayer.py", line 105, in build_targets
,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0    iou, ciou = bbox_xywha_ciou(pred_boxes[b, best_n, gj, gi], target_boxes)
], thread: [42  File "/home/dio/VSST/zwm/remote_sensing_detection/Demo/R-YOLOv4-main/model/loss.py", line 63, in bbox_xywha_ciou
,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"    inter_min_xy = torch.max(pred_boxes[:, :2], target_boxes[:, :2])
` failed.
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [44,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [45,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [46,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [48,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [49,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [50,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [52,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [53,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [54,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [56,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [57,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [58,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [60,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [8,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [9,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [10,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [12,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [13,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [14,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [16,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [17,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [18,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [20,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [21,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [24,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [25,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [26,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [28,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [29,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [30,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

**Comment by yingkunwu** [comment]
I didn't run into this error before, seems like an environment problem. Can you try installing the environment with python3.8?

**Comment by xiaofeng-c** [comment]
OK,i will try it.

**Comment by xiaofeng-c** [comment]
Thank you,i sucessfully solve this question.

**Comment by xiaofeng-c** [comment]
Do you know how to label our own datasets with the same format  as UCAS-AOD datasets  do?

**Comment by yingkunwu** [comment]
I use [labelImg2](https://github.com/chinakook/labelImg2) to label my custom dataset. It is a useful tool. However, the format created by it is different from the format used by UCAS-AOD. Therefore some code modification in tools/load.py is needed.

**Comment by xiaofeng-c** [comment]
Ok,thank you for your help!I will give a try.

**Comment by PJPomPom** [comment]
> Whether it can be trained in 1 GPU?

您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了

**Comment by yingkunwu** [comment]
> > Whether it can be trained in 1 GPU?
> 
> 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了

UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。

**Comment by PJPomPom** [comment]
> > > Whether it can be trained in 1 GPU?
> > 
> > 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了
> 
> UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。

嗯呐，我现在已经有具体的数据集了，只是我转化为txt之后呢，按照教程训练出问题了，我在想是不是我这个训练步骤出错了，所以想拜托大佬赐教一下，教我一下具体训练步骤🤣

**Comment by PJPomPom** [comment]
> > > Whether it can be trained in 1 GPU?
> > 
> > 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了
> 
> UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。

嗯啦，我找到了一个数据集，将xml转化为txt文件后训练出现问题，我在想是不是我的训练步骤不对呢，所以想问大佬赐教一下具体训练步骤🤣

**Comment by yingkunwu** [comment]
> > > > Whether it can be trained in 1 GPU?
> > > 
> > > 
> > > 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了
> > 
> > 
> > UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。
> 
> 嗯啦，我找到了一个数据集，将xml转化为txt文件后训练出现问题，我在想是不是我的训练步骤不对呢，所以想问大佬赐教一下具体训练步骤🤣

如果格式一樣的話應該是沒有問題的，你可以確認一下你輸出的txt文件中的data格式是否符合以下的安排：

Label: x1, y1, x2, y2, x3, y3, x4, y4, theta, x, y, width, height 
(x1, y1) is the coordinate located on the upper left of the bounding box, and then (x2, y2), (x3, y3) and (x4, y4) following the clockwise order respectively.

如果是model在訓練過程中發生錯誤，你可以把錯誤給貼上來，thanks!

**Comment by PJPomPom** [comment]
> > > > > Whether it can be trained in 1 GPU?
> > > > 
> > > > 
> > > > 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了
> > > 
> > > 
> > > UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。
> > 
> > 
> > 嗯啦，我找到了一个数据集，将xml转化为txt文件后训练出现问题，我在想是不是我的训练步骤不对呢，所以想问大佬赐教一下具体训练步骤🤣
> 
> 如果格式一樣的話應該是沒有問題的，你可以確認一下你輸出的txt文件中的data格式是否符合以下的安排：
> 
> Label: x1, y1, x2, y2, x3, y3, x4, y4, theta, x, y, width, height (x1, y1) is the coordinate located on the upper left of the bounding box, and then (x2, y2), (x3, y3) and (x4, y4) following the clockwise order respectively.
> 
> 如果是model在訓練過程中發生錯誤，你可以把錯誤給貼上來，thanks!
🆗

**Comment by PJPomPom** [comment]
> > > > > > Whether it can be trained in 1 GPU?
> > > > > 
> > > > > 
> > > > > 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了
> > > > 
> > > > 
> > > > UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。
> > > 
> > > 
> > > 嗯啦，我找到了一个数据集，将xml转化为txt文件后训练出现问题，我在想是不是我的训练步骤不对呢，所以想问大佬赐教一下具体训练步骤🤣
> > 
> > 如果格式一樣的話應該是沒有問題的，你可以確認一下你輸出的txt文件中的data格式是否符合以下的安排：
> > 
> > Label: x1, y1, x2, y2, x3, y3, x4, y4, theta, x, y, width, height (x1, y1) is the coordinate located on the upper left of the bounding box, and then (x2, y2), (x3, y3) and (x4, y4) following the clockwise order respectively.
> > 
> > 如果是model在訓練過程中發生錯誤，你可以把錯誤給貼上來，thanks!
> 🆗

我将再次尝试，大佬您有空的时候回复我就行的😬

**Comment by PJPomPom** [comment]
> > > > > > > Whether it can be trained in 1 GPU?
> > > > > > 
> > > > > > 
> > > > > > 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了
> > > > > 
> > > > > 
> > > > > UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。
> > > > 
> > > > 
> > > > 嗯啦，我找到了一个数据集，将xml转化为txt文件后训练出现问题，我在想是不是我的训练步骤不对呢，所以想问大佬赐教一下具体训练步骤🤣
> > > 
> > > 
> > > 如果格式一樣的話應該是沒有問題的，你可以確認一下你輸出的txt文件中的data格式是否符合以下的安排：
> > > Label: x1, y1, x2, y2, x3, y3, x4, y4, theta, x, y, width, height (x1, y1) is the coordinate located on the upper left of the bounding box, and then (x2, y2), (x3, y3) and (x4, y4) following the clockwise order respectively.
> > > 如果是model在訓練過程中發生錯誤，你可以把錯誤給貼上來，thanks!
> > > 🆗
> 
> 我将再次尝试，大佬您有空的时候回复我就行的😬

![241e9e8e9a0286db7687aa98c77dee9](https://user-images.githubusercontent.com/77728649/143214401-2802015f-70fb-4a22-8881-e0f6b02cc34a.png)
![de129950a26d8c607ae1cb0585b0b67](https://user-images.githubusercontent.com/77728649/143214472-237a70ab-a56f-4c84-833c-2483b55622c7.png)
![3d4594728f67ae0f82679965f9bf37d](https://user-images.githubusercontent.com/77728649/143214507-b02a01bb-a7e0-4855-9b16-20f5a2958812.png)
这是我生成txt格式的代码，我是单一目标，格式我是按照UCAS-AOD的科学计数法来的，我换掉格式还是不对呢

**Comment by yingkunwu** [comment]
> > > > > > > Whether it can be trained in 1 GPU?
> > > > > > 
> > > > > > 
> > > > > > 您好，请问能具体讲一下你使用UCAS-AOD数据集的每一步训练的步骤嘛，我通过labelimg2得到xml转化为txt后，训练出现问题了
> > > > > 
> > > > > 
> > > > > UCAS-AOD 不用使用labelimg2來label喔，他們的資料及本身就有label了。labelimg2的目的是要label自己想要訓練的資料集。
> > > > 
> > > > 
> > > > 嗯啦，我找到了一个数据集，将xml转化为txt文件后训练出现问题，我在想是不是我的训练步骤不对呢，所以想问大佬赐教一下具体训练步骤🤣
> > > 
> > > 
> > > 如果格式一樣的話應該是沒有問題的，你可以確認一下你輸出的txt文件中的data格式是否符合以下的安排：
> > > Label: x1, y1, x2, y2, x3, y3, x4, y4, theta, x, y, width, height (x1, y1) is the coordinate located on the upper left of the bounding box, and then (x2, y2), (x3, y3) and (x4, y4) following the clockwise order respectively.
> > > 如果是model在訓練過程中發生錯誤，你可以把錯誤給貼上來，thanks!
> > > 🆗
> 
> 我将再次尝试，大佬您有空的时候回复我就行的😬

好喔，如果還有問題的話麻煩幫我開一個新issue，這個舊的我先關了。

**Comment by Endrhythm** [comment]
> Thank you,i sucessfully solve this question.

Can you share your trick?

**Comment by Endrhythm** [comment]
> > Thank you,i sucessfully solve this question.
> 
> Can you share your trick?

Actually, the label should start from 0.
